def shared_pods
  pod 'Onboarding'
end

target 'WalletBank' do
  use_frameworks!

  shared_pods
  
  target 'WalletBankTests' do
    inherit! :search_paths
   
  end

  target 'WalletBankUITests' do
    
  end

end
